name: Electron CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: fe npm install
        run: |
          cd fe && npm install
      - name: main npm install
        run: |
          cd main && npm install
      - name: tools npm install
        run: |
          cd tools && npm install
      - name: fetch ipfsbin
        run: |
          cd tools && node fetchKubo.js
      - name: build package
        run: |
          cd main && npm run make      
      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: ${{ github.ref }}
      #     body_path: CHANGELOG.md
      #     draft: false
      #     prerelease: true
      # - name: upload apk
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./build/app/outputs/flutter-apk/app-release.apk
      #     asset_name: scbrf-release.apk
      #     asset_content_type: application/vnd.android.package-archive
