name: Electron CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: tools npm install
        run: |
          cd tools && npm install
      - name: fetch ipfsbin
        run: |
          cd tools && node fetchKubo.js
      - name: fe npm install
        run: |
          cd fe && npm install
      - name: main npm install
        run: |
          cd main && npm install
      - name: build package
        run: |
          cd main && npm run make
      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            "main/out/make/**/*.zip"
            "main/out/make/**/*.exe"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
